export const Cards = [
    { MajorArcana: {
        Fool: {
            name: "The Fool",
            rank: '0',
            number: 0,
            upright: '(Beginnings, innocence, spontaneity, opportunity  free-spirited)',
            reversed: '(Risk-taking, false-start,recklessness, holding back, apathy, ignoring an opportunity)',
            description: 'The Fool description here...',
            rev_description: 'The Fool reversed description here...',
            suit: 'Major',
        },
        Magician: {
            name: "The Magician",
            rank: 'I',
            number: 1,
            upright: '(Manifestation, inspiration, empowered thoughts, diplomacy, communication)',
            reversed: '(Delays, deception, disempowered thoughts, manipulation, avoidance)',
            description: 'The Magician description here...',
            suit: 'Major',
        },
        HighPriestess: {
            name: "The High Priestess",
            rank: 'II',
            number: 2,
            upright: '(Intuition, divine feminine, dreams, subconcious mind)',
            reversed: '(Secrets, withdrawal, silence, disconnection)',
            description: 'The High Priestess description here...',
            suit: 'Major',
        },
        Empress: {
            name: "The Empress",
            rank: 'III',
            number: 3,
            upright: '(Femininity, fertility, beauty, nurture, abundance, peace, security, creativity)',
            reversed: '(Creative block, dependence, imbalance, insecurity, relationships suffer)',
            description: 'The Empress description here...',
            suit: 'Major',
        },
        Emperor: {
            name: "The Emperor",
            rank: 'IV',
            number: 4,
            upright: '(Masculinity, authority, structure, protection, support, order)',
            reversed: '(Domination, abuse of power, excessive control, lack of discipline, inflexibility, greed)',
            description: 'description here...',
            suit: 'Major',
        },
        Hierophant: {
            name: "The Hierophant",
            rank: 'V',
            number: 5,
            upright: '(Tradition, orthodoxy, conformity, spiritual wisdom, unity, alliance, commitment) )',
            reversed: '(Segregation, radical ideals, freedom, challenging the status quo, misleading a group)',
            description: 'description here...',
            suit: 'Major',
        },
        Lovers: {
            name: "The Lovers",
            rank: 'VI',
            number: 6,
            upright: '(Love, harmony, attraction, bonding, alignment of values, decisions, maturity)',
            reversed: '(Self-love, disharmony, repulsion, misalignment of values, lust over love)',
            description: 'description here...',
            suit: 'Major',
        },
        Chariot: {
            name: "The Chariot",
            rank: 'VII',
            number: 7,
            upright: '(Action, progress, energy, determination, victory, mastery, journey)',
            reversed: '(Opposition, roadblocks, lack of direction, confusion, scattered energy, failure)',
            description: 'description here...',
            suit: 'Major',
        },
        Strength: {
            name: "Strength",
            rank: 'VIII',
            number: 8,
            upright: '(Strength, courage, patience, compassion, resilience, physical strength, health)',
            reversed: '(Fear, self-doubt, impatience, cowardice, physical weakness, avoiding a challenge)',
            description: 'description here...',
            suit: 'Major',
        },
        Hermit: {
            name: "The Hermit",
            rank: 'IX',
            number: 9,
            upright: '(Introspection, solitude, reflection, inner guidance, self-healing)',
            reversed: '(Isolation - unwanted/unexpected, withdrawal, loneliness, lack of support)',
            description: 'description here...',
            suit: 'Major',
        },
        WheelOfFortune: {
            name: "The Wheel of Fortune",
            rank: 'X',
            number: 10,
            upright: '(Fate, destiny, karma, good luck, change, opportunity)',
            reversed: '(Resistance to change, bad luck, breaking cycles, disruption, disconnection)',
            description: 'description here...',
            suit: 'Major',
        },
        Justice: {
            name: "Justice",
            rank: 'XI',
            number: 11,
            upright: '(Justice, fairness, truth, balance, law, cause & effect, accountability)',
            reversed: '(Unfairness, lack of accountability, dishonesty, miscarriage of justice)',
            description: 'description here...',
            suit: 'Major',
        },
        HangedMan: {
            name: "The Hanged Man",
            rank: 'XII',
            number: 12,
            upright: '(Suspension, time, waiting, transition, reversals, sacrifice)',
            reversed: '(Stalling, indecision, delays, resistance, wasting time, time for action)',
            description: 'description here...',
            suit: 'Major',
        },
        Death: {
            name: "Death",
            rank: 'XIII',
            number: 13,
            upright: '(Endings, change, transformation, transition, letting go)',
            reversed: '(Resistance to change, holding on, anger, regret, shock, stress)',
            description: 'description here...',
            suit: 'Major',
        },
        Temperance: {
            name: "Temperance",
            rank: 'XIV',
            number: 14,
            upright: '(Balance, moderation, reconciliation, adjustment)',
            reversed: '(Imbalance, excess, re-alignment, living in past / future, feeling overwhelmed)',
            description: 'description here...',
            suit: 'Major',
        },
        Devil: {
            name: "The Devil",
            rank: 'XV',
            number: 15,
            upright: '(Addiction, temptation, restriction, lust, shadow self, anger, materialism)',
            reversed: '(Releasing limiting beliefs, breaking a (bad) habit, detachment, confronting dark thoughts)',
            description: 'description here...',
            suit: 'Major',
        },
        Tower: {
            name: "The Tower",
            rank: 'XVI',
            number: 16,
            upright: '(Upheaval, sudden change, chaos, revelation, awakening, destruction, illumination, shock)',
            reversed: '(Fear of change, averting disaster, personal transformation, self-blame for events out of your control)',
            description: 'description here...',
            suit: 'Major',
        },
        Star: {
            name: "The Star",
            rank: 'XVII',
            number: 17,
            upright: '(Hope, faith, purpose, renewal, healing, wishes, inspiration, guidance)',
            reversed: '(Despair, disbelief, uncertainty, lack of faith, lack of perseverance, lack of support)',
            description: 'description here...',
            suit: 'Major',
        },
        Moon: {
            name: "The Moon",
            rank: 'XVIII',
            number: 18,
            upright: '(Illusion, subconscious, mystery, dreams, indecision, deception, fear)',
            reversed: '(Repressed emotion, release of fear, inner confusion, downgrading expectations)',
            description: '',
            suit: 'Major',
        },
        Sun: {
            name: "The Sun",
            rank: 'XIX',
            number: 19,
            upright: '(Positivity, optimism, warmth, fun, success, vitality, family, well-being)',
            reversed: '(Temporariliy: overly optimistic, struggling to see the sun, or feeling clouded)',
            description: '',
            suit: 'Major',
        },
        Judgment: {
            name: "Judgment",
            rank: 'XX',
            number: 20,
            upright: '(Judgment, rebirth, absolution, inner calling, the past, memories, awakening)',
            reversed: '(Inner critic, self-doubt, ignoring the call, past disrupts the present, guilt, trapped in the past, grieving)',
            description: '',
            suit: 'Major',
        },
        World: {
            name: "The World",
            rank: 'XXI',
            number: 21,
            upright: '(Completion, success, accomplishment, reward, integration, expansion, travel)',
            reversed: '(Delays, short-cuts, perfectionism, clinging to unrealistic goals, pressure to perform)',
            description: '',
            suit: 'Major',
        },
    }},
    { MinorArcana: {
        Swords: {
            Ace: {
                name: 'Ace of Swords',
                rank: 'Ace',
                number: 1,
                keywords: '(Ace of Swords keywords here...)',
                description: 'Ace of Swords description here...',
                suit: 'Swords',
            }
        },
        Cups: {

        },
        Wands: {

        },
        Pentacles: {

        }

    }
}
]